version: '3'
services:
  php-app:
    image: php-oracle
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - oracle-db
    networks:
      - my-network

  oracle-db:
    image: oracleinanutshell/oracle-xe-11g  
    volumes:
      - oracle_data:/u01/app/oracle
    ports:
      - 1521:1521
    networks:
      - my-network

networks:
  my-network:

volumes:
  oracle_data:
